## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [12]:
arr = np.random.randint(0, 30, size=10)
print("Исходный массив:", arr)
arr[(arr > 3) & (arr < 8)] *= -1
print("Массив после изменений:", arr)

Исходный массив: [ 9  4 12  1 29 11 29  6  8 28]
Массив после изменений: [ 9 -4 12  1 29 11 29 -6  8 28]


**2.** Заменить максимальный элемент случайного массива на 0

In [17]:
max_index = np.argmax(arr)
arr[max_index] = 0
print("Индекс максимальманого значения в массиве: ", max_index)
print("Массив после замены max value на 0:", arr)

Индекс максимальманого значения в массиве:  9
Массив после замены max value на 0: [ 9 -4 12  1  0 11  0 -6  8  0]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [26]:
# Решение найдено с помощью интернета
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [19]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 4 5 6 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [20]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 0 4]
 [4 1 0]
 [3 1 2]
 [1 3 2]
 [0 3 1]
 [3 0 4]
 [1 2 3]
 [2 3 4]
 [2 0 4]
 [1 4 2]]
[[4 0 4]
 [4 1 0]
 [3 1 2]
 [1 3 2]
 [0 3 1]
 [3 0 4]
 [1 2 3]
 [2 3 4]
 [2 0 4]
 [1 4 2]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [23]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9],
                [4, 5, 6]])
unique_rows = np.unique(arr, axis=0)
print("Исходный двумерный массив:", arr)
print("Массив после удаления повторяющихся строк:")
print(unique_rows)

Исходный двумерный массив: [[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]]
Массив после удаления повторяющихся строк:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [29]:
# Python
def diag_product_no_numpy(arr):
    prod = 1
    for i in range(min(len(arr), len(arr[0]))):
        if arr[i][i] != 0:
            prod *= arr[i][i]
    return prod

arr = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
print("Python:", diag_product_no_numpy(arr))

# Numpy
def diag_product_numpy(arr_n):
    return np.prod(np.diag(arr_n)[np.diag(arr_n) != 0])

arr_n = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
print("Nympy:", diag_product_numpy(arr_n)) 

Python: 3
Nympy: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [32]:
x = list([1, 2, 2, 4])
y = list([4, 2, 1, 2])

# Python
def is_same_multiset_no_numpy(x, y):
    return sorted(x) == sorted(y)

# Numpy
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])
def is_same_multiset_numpy(x, y):
    return np.array_equal(np.sort(x), np.sort(y))

print("Python:", is_same_multiset_no_numpy(x, y))
print("Numpy:", is_same_multiset_numpy(x, y))

Python: True
Numpy: True


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [33]:
# Python
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]

def max_after_zero_no_numpy(x):
    max_elem = float('-inf')
    for i in range(1, len(x)):
        if x[i-1] == 0:
            max_elem = max(max_elem, x[i])
    return max_elem

print("Python:", max_after_zero_no_numpy(x))

# Numpy
arr = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])

def max_after_zero_numpy(x):
    return np.max(x[1:][x[:-1] == 0])

print("Numpy:", max_after_zero_numpy(arr))

Python: 5
Numpy: 5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [37]:
# Python
x = [2, 2, 2, 3, 3, 3, 5]

def run_length_encoding_no_numpy(x):
    values = []
    counts = []
    
    current_value = x[0]
    count = 1
    
    for i in range(1, len(x)):
        if x[i] == current_value:
            count += 1
        else:
            values.append(current_value)
            counts.append(count)
            current_value = x[i]
            count = 1
    
    values.append(current_value)
    counts.append(count)
    
    return values, counts

print("Python:", run_length_encoding_no_numpy(x))

# Numpy
arr = np.array([2, 2, 2, 3, 3, 3, 5])

def run_length_encoding_numpy(arr):
    diff = np.diff(arr, prepend=arr[0] - 1)
    values = arr[diff != 0]
    counts = np.diff(np.flatnonzero(np.r_[diff != 0, True]))
    return values, counts

print("Numpy: ", run_length_encoding_numpy(arr))

Python: ([2, 3, 5], [3, 3, 1])
Numpy:  (array([2, 3, 5]), array([3, 3, 1]))


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [38]:
# Python
import math

X = [[1, 2], [3, 4]]
Y = [[5, 6], [7, 8]]

def euclidean_distance_matrix_no_numpy(X, Y):
    result = []
    for x in X:
        row = []
        for y in Y:
            dist = math.sqrt(sum((xi - yi) ** 2 for xi, yi in zip(x, y)))
            row.append(dist)
        result.append(row)
    return result

print("Python: ", euclidean_distance_matrix_no_numpy(X, Y))

# Numpy
arr_X = np.array([[1, 2], [3, 4]])
arr_Y = np.array([[5, 6], [7, 8]])

def euclidean_distance_matrix_numpy(arr_X, arr_Y):
    return np.sqrt(np.sum((arr_X[:, np.newaxis] - arr_Y) ** 2, axis=2))

print("Numpy: ", euclidean_distance_matrix_numpy(arr_X, arr_Y))

Python:  [[5.656854249492381, 8.48528137423857], [2.8284271247461903, 5.656854249492381]]
Numpy:  [[5.65685425 8.48528137]
 [2.82842712 5.65685425]]


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [2]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [3]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [11]:
average_calories = np.mean(calorie_stats)
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [13]:
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [25]:
median_calorie_stats = np.median(calorie_stats)
print(median_calorie_stats)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [17]:
nth_percentile = np.percentile(calorie_stats, np.arange(1, 101, 1))
first_above_60 = np.min(nth_percentile[nth_percentile > 60])
print(f"Наименьший процентиль, превышающий 60 калорий: {first_above_60}")

Наименьший процентиль, превышающий 60 калорий: 70.0


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [18]:
more_calories = np.sum(calorie_stats > 60) / len(calorie_stats) * 100
print(f"Процент хлопьев с более чем 60 калориями: {more_calories:.2f}%")

Процент хлопьев с более чем 60 калориями: 96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [19]:
calorie_std = np.std(calorie_stats)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [30]:
print(f"""По данным о калориях CrunchieMunchies, среднее количество калорий составляет {average_calories:.2f}, 
а медиана — {median_calorie_stats:.2f}. Это значит, что хотя среднее значение выглядит высоким, '
медиана показывает, что половина продуктов содержит больше калорий. Более того, {more_calories:.2f}% '
конкурентов превышает 60 калорий на порцию. Это хороший аргумент для продвижения CrunchieMunchies '
как более здорового варианта. Стандартное отклонение также показывает, что калорийность конкурентов '
различается, что может привлечь внимание к более здоровым продуктам, таким как CrunchieMunchies.""")

По данным о калориях CrunchieMunchies, среднее количество калорий составляет 106.88, 
а медиана — 110.00. Это значит, что хотя среднее значение выглядит высоким, '
медиана показывает, что половина продуктов содержит больше калорий. Более того, 96.10% '
конкурентов превышает 60 калорий на порцию. Это хороший аргумент для продвижения CrunchieMunchies '
как более здорового варианта. Стандартное отклонение также показывает, что калорийность конкурентов '
различается, что может привлечь внимание к более здоровым продуктам, таким как CrunchieMunchies.
